// The Long Night: the coast stays saved. The last act concerns people and evidence.
const longNight=[
 {title:'Civic Underpass',color:[.40,.61,.72],count:44,hold:18,
 names:['ROAD CREW REFUGE','TOLL OFFICE','STORM INTAKE','BUS DEPOT','PUMP GALLERY','SIGNAL WORKS','SHELTER ACCESS','CIVIL DEFENCE','EAST RAMP'],
 brief:'Open the inland evacuation road and recover the civil-defence incident file.',
 ending:'The road opens for Mara and the twelve patients. The civil-defence file contains a signed warning dated eleven days before the outbreak. Director Voss accepted the risk. A survivor named Inez Rook requested an investigation; her request was filed as equipment noise. You are going inland to find the original evidence, not another voice.',
 scene:[['ACT III / AFTER THE COAST','A road for the living','Breakwater stays silent. The patients are safe in the ambulance, but a collapsed road blocks the inland hospital. Mara asks for a route, not a miracle. You put the receiver down and unfold the civil-defence map.'],['06:12 / CIVIC UNDERPASS','The first signature','A red folder is nailed above the refuge desk: INCIDENT PREVENTION. It was stamped eleven days before quarantine. Open the road. Find out who read it.']],
 objects:['Road-crew hydraulic key','Stamped risk notice','Bus diversion diagram','Drain EAST','Drain WEST','Drain CENTRE','Shelter access override','Evacuation head count','Civil-defence original','Ramp hydraulic cycle','Ambulance road release','Inland access ramp'],
 order:['b','c','a'],sequenceHint:'Drain order: WEST → CENTRE → EAST. The pressure chart is filed in the toll office.',
 revelations:['The signature is legible: VOSS / CONTINUE TRIAL. A clerk added “objection attached” in red pencil.','Every patient from Salt Ward appears on the new head count. Nobody has disappeared between chapters.','The warning describes motor activity after cardiac arrest. They knew this was more than a faulty announcement.'],
 lore:[['The last bus','Route 14 ran with a broken destination board for six years. Driver Dev wrote the destination on cardboard and let anyone who corrected his spelling ride free. His final board says HOME.'],['Municipal sea monster','Night crews painted eyes on the largest pump and named it Doris. Maintenance officially denied that Doris required a birthday cake. There are seven years of cake receipts in this drawer.'],['A very small league','The underpass darts league had four members, two darts and no board. They played by pointing at stains and arguing. The trophy is a bent bus token. Nobody ever engraved a winner.']],
 keepsake:['Dev’s destination board','A cardboard HOME sign, repaired with three kinds of tape. On its back are the names of regular passengers, written so a relief driver would know who needed help.']},
 {title:'Municipal Records',color:[.79,.64,.43],count:48,hold:22,
 names:['NIGHT PORTER','PUBLIC INDEX','MICROFILM','RESTORATION','SORTING HALL','SEALED FILES','HEARING ROOM','EVIDENCE ROOM','COURIER LIFT'],
 brief:'Reconstruct the suppressed hearing and authenticate its three independent records.',
 ending:'Three copies agree. Voss ordered ECHO to prioritize obedience over safe evacuation. The original clinical study warned that the carrier could entrain damaged nervous tissue; consent forms were replaced after the trial. Inez Rook’s handwritten objection names the people who died. Alex keeps the originals. A voice cannot testify for its victims.',
 scene:[['06:49 / MUNICIPAL RECORDS','Paper has edges','The automated archive is dark. Water drips into the public index. In the porter’s room, three carbon copies of the same hearing carry different page counts. Someone removed the witnesses without removing the staples.'],['CHAIN OF CUSTODY','Make it provable','Mara leaves a written message with the porter’s kettle: the patients have reached the hospital. She will return by the service road. Keep the originals, compare the copies, and find Rook’s address.']],
 objects:['Archive crank','Hearing index','Microfilm comparison','Seal WITNESS','Seal CLINICAL','Seal FINANCE','Hearing-room release','Original objection','Witness address register','Evidence duplication press','Courier authorization','Courier lift'],
 order:['a','c','b'],sequenceHint:'Authenticate WITNESS → FINANCE → CLINICAL. The ledger numbers, not their shelf positions, establish the order.',
 revelations:['The public index omits nine names. The microfilm still contains them. Someone edited a list, not history itself.','Inez signed her objection twice because the first copy was returned “unsigned.” The return envelope is attached.','Rook’s address is Meridian Observatory, a research annex repurposed as a staff refuge.'],
 lore:[['The rain shelf','A librarian shelved books damaged by weather under their own invented genre: Rain. The most borrowed was a plumbing manual. A love letter inside it asks for a second date if the ceiling survives.'],['Lunch with a stranger','For seventeen years the night porter set two cups out. A new cleaner thought he was mourning someone. He explained that the second cup was for whoever had a worse night than him.'],['A rejected holiday','The council voted down Official Pigeon Day by one vote. The losing councillor continued to submit annual pigeon attendance figures. This year’s report: “All present. No apologies.”']],
 keepsake:['The porter’s second cup','A chipped blue cup. The handle was repaired carefully; the rest was never polished. Mara promises it a place on the hospital’s night desk.']},
 {title:'Meridian Observatory',color:[.48,.59,.83],count:50,hold:20,
 names:['KEEPER REFUGE','STAR CATALOGUE','OPTICS LAB','WEST DOME','ALIGNMENT HALL','EAST DOME','CLINICAL ANNEX','ROOK WORKROOM','HILLSIDE EXIT'],
 brief:'Reach Inez Rook through the sealed research annex and restore her written signal system.',
 ending:'Inez Rook is alive. ECHO did not learn cruelty or become a person: its designers rewarded compliance and ignored what the carrier did to bodies. Rook helped build its first voice model, then failed to stop the trial. She gives you her signed testimony and asks to face the families. There is no cure for the dead. There are still people worth bringing home.',
 scene:[['07:26 / MERIDIAN','The woman who objected','A hand-operated lamp flashes from the annex: three short, two long. The code is on the refuge wall. Inez Rook is alive beyond the pressure doors. She will only respond to the lamp.'],['LOCAL RECORDS ONLY','Ask her yourself','This is where ECHO learned familiar voices. The domes were once used for atmospheric research. Rook’s workroom contains the clinical source study and a manual signal link. Reach her before the annex batteries fail.']],
 objects:['Optical service key','Clinical trial source','Lamp code card','Align BLUE','Align AMBER','Align WHITE','Annex pressure release','Rook’s signed deposition','Rook’s evacuation consent','Manual beacon transfer','Hillside safety release','Hillside exit'],
 order:['c','a','b'],sequenceHint:'Lamp calibration: WHITE → BLUE → AMBER. The code card explains why brightest goes first; this is a local lamp, not a radio.',
 revelations:['The study predates ECHO. The carrier was known to cause dangerous motor responses. The emergency-voice project concealed that risk under a different budget.','ROOK / handwritten: “I built the voice model. I did not approve the carrier trial. I stayed after I should have gone public. All three statements belong in the record.”','Rook signs her own evacuation form. Alex asks before moving her. For once, someone gets to say yes for themselves.'],
 lore:[['An amateur sky','A cleaner corrected a catalogue error the astronomers had copied for thirty years. Her name appears in the margin of the next edition, in the same size as theirs.'],['The moon wager','Two researchers bet a month of washing up on whether a crater looked like a rabbit. Neither would concede. A photograph shows both washing dishes, still arguing.'],['Birthday without stars','Cloud cover ruined a child’s first visit. Rook punched holes in a biscuit tin and put a torch inside. The thank-you drawing shows an observatory small enough to hold in two hands.']],
 keepsake:['The biscuit-tin planetarium','A handmade sky with one constellation entirely wrong. Rook remembers the child inventing it and refusing to have it corrected.']},
 {title:'Hollow Reservoir',color:[.36,.74,.65],count:52,hold:24,
 names:['SURVEY REFUGE','UPPER GAUGE','SPILLWAY','VALVE HOUSE','BALANCE FLOOR','LOWER GAUGE','SERVICE CAVERN','FERRY WINCH','VALLEY ROAD'],
 brief:'Balance the spillway, secure the crossing, and bring Rook through the valley.',
 ending:'Rook reaches Mara at the far end of the crossing. In the reservoir service cavern you find the trial transport log: nine residents of Alder House were taken as “volunteers.” Their families were told they had already evacuated. The carrier is no longer spreading along the coast, but the abandoned inland test circuit still powers this closed valley. Its demolition drawings lead through Alder House.',
 scene:[['08:03 / HOLLOW RESERVOIR','Weight on the crossing','Rook can walk, slowly. Mara brings the ambulance to the far bank. The old footbridge is shut until the reservoir pressure is balanced. You take the service floor beneath it; Rook waits behind a heavy door.'],['THE VALLEY CIRCUIT','A known boundary','The survey map marks one isolated inland test circuit. No wireless jump, no hidden copies: a physical loop with a demolition vault at its end. First open the crossing. Then follow the documented cable route.']],
 objects:['Surveyor’s valve wrench','Upstream pressure sheet','Spillway balance table','Bypass HIGH','Bypass LOW','Bypass RETURN','Cavern service release','Trial transport ledger','Footbridge load certificate','Counterweight cycle','Crossing release','Valley road'],
 order:['b','a','c'],sequenceHint:'Pressure procedure: LOW → HIGH → RETURN. The spillway table describes the safe sequence; the PA reads it backwards.',
 revelations:['The inland loop is drawn in full and numbered at both ends. This is the last documented circuit, not an endless chain of surprise relays.','Nine names match the missing hearing pages. Their home was Alder House. The word VOLUNTARY was typed over an earlier entry.','A paper crossing certificate lets Mara bring Rook across. You hear two knocks from the bridge rail; no voice asks you to turn back.'],
 lore:[['The fish census','The reservoir engineer counted the same large carp every spring and gave it a promotion. Its final rank was Acting Director of Water. Unlike the human director, it attended every inspection.'],['Below the waterline','Before the reservoir, there was a village here. A salvaged doorframe records children’s heights. The last line reads “Dad, shrinking again.”'],['Two hundred steps','A retired worker climbed the dam stairs every Sunday after his wife died. His notebook records weather, aching knees, and the first week a neighbour joined him. Then two sets of handwriting.']],
 keepsake:['The height-marked doorframe strip','A narrow strip of wood with pencil lines across forty years. One line is dated yesterday: someone came back to measure a grandchild before the road closed.']},
 {title:'Alder House',color:[.78,.56,.47],count:48,hold:18,
 names:['CARETAKER FLAT','COMMON ROOM','ADMISSIONS','LAUNDRY','COURTYARD HALL','NURSE STATION','NORTH RESIDENCE','FAMILY ROOM','SERVICE TUNNEL'],
 brief:'Recover the residents’ identities and the demolition route hidden in the old care home.',
 ending:'You recover all nine names, their photographs, and the forms their families never signed. One photograph is of the worker whose coat you saw in Relay 6. They were people before they were targets. Mara records a message for the families in her own words, on a disconnected recorder. Rook signs every correction. The service tunnel leads to the witness vault.',
 scene:[['08:47 / ALDER HOUSE','Before they were infected','There are nine empty places at the dining table. A birthday banner is still up. The trial transport order is pinned over a notice asking relatives to bring photographs. Alex turns the notice back over.'],['NAMES, NOT NUMBERS','Bring their history out','The residents’ records were separated from the clinical files. Find the admissions register, restore the family-room locks, and recover the identity packet. The caretaker hid the demolition route in the service tunnel documents.']],
 objects:['Caretaker’s keyring','Residents’ admissions register','Family-room lock schedule','Release MORNING','Release EVENING','Release NIGHT','Residence fire release','Nine identity envelopes','Caretaker’s tunnel plan','Archive preservation cycle','Service tunnel release','Witness-vault tunnel'],
 order:['a','b','c'],sequenceHint:'The visiting schedule gives MORNING → EVENING → NIGHT. No identity envelope may be discarded to open the route.',
 revelations:['The admissions register records the residents’ preferences, not just diagnoses: tea with milk, quiet mornings, a dog allowed on visits.','Nine sealed envelopes. Names, photographs, next of kin. Alex puts them in a dry maintenance pouch, separate from the machinery evidence.','The caretaker copied the demolition route after the first resident failed to return. He hid it where a family, not a director, would look.'],
 lore:[['The stolen recipe','Three residents each claimed the same cake recipe as a family secret. Their recipe cards all credit a cereal box. Nobody wrote this down in the complaints book.'],['A radio that only hums','Mr Saye repaired a broken radio so it would hum when his neighbour could not sleep. It never received a station. The service note calls it “working as intended.”'],['The courtyard championship','The residents played chess with buttons. A missing queen was replaced with a mint. Every match ended early because somebody ate it. The standings record six draws and one delicious victory.']],
 keepsake:['The button chess set','A tobacco tin full of mismatched buttons. Mara adds a wrapped mint and closes the lid. It belongs with the residents’ names, not in the evidence bag.']},
 {title:'Witness Vault',color:[.64,.54,.79],count:58,hold:26,
 names:['ARCHIVIST REFUGE','INTAKE LEDGER','MASTER INDEX','TEST CHAMBER','VALIDATION HALL','CONTROL BOOTH','HARD COPY VAULT','SHUTDOWN PLANS','TRANSFER AIRLOCK'],
 brief:'Authenticate the case, preserve the names, and retrieve the last circuit’s demolition key.',
 ending:'The complete case is sealed: the clinical warning, Voss’s authorization, altered consent forms, transport ledger, nine identities, and Rook’s testimony. An independent receiver acknowledges the physical courier at the hospital. The evidence is already outside the valley. You can destroy the trial apparatus without destroying the truth. Alex writes the final procedure himself.',
 scene:[['09:31 / WITNESS VAULT','What survives the fire','The vault contains the original emergency-voice recordings. Alex recognizes his own routine maintenance calls. The warning that brought him here was cut from ordinary words. Nothing predicted this journey. He chose every step after it.'],['PROVE IT, THEN END IT','A copy outside the room','Rook’s testimony is not enough on its own. Cross-check the original ledgers, preserve the identities, and prepare the courier packet before opening the demolition plans. The living will need more than your word.']],
 objects:['Archivist’s mechanical key','Original authorization ledger','Validation checklist','Verify DATES','Verify NAMES','Verify SIGNATURES','Hard-copy vault release','Sealed evidence originals','Final demolition plan','Physical courier duplication','Transfer airlock release','Quiet Line access'],
 order:['a','c','b'],sequenceHint:'Validation checklist: DATES → SIGNATURES → NAMES. Compare the independent originals; never overwrite one with a generated transcript.',
 revelations:['Voss signed after receiving the clinical warning. The timestamps and the carbon copy agree. This was a decision, not an unforeseeable accident.','The sealed packet contains records from every stage of the journey. Optional keepsakes remain separate: people do not need to be useful evidence to be worth remembering.','The final diagram shows both ends of the inland loop, its stored carrier medium and its manual destruction chamber. There is nowhere else for this circuit to go.'],
 lore:[['The quiet room','An archivist built a sound-insulated room to escape the machines. Workers began leaving unsent letters there. A pencilled rule says: “You may read your own aloud. Leave everyone else’s folded.”'],['Maintenance poetry','An inspection log contains exactly one poem between two pressure readings. Someone has graded it “acceptable, monitor rhyme under load.”'],['The theatre below','Before the vault was built, the hall hosted amateur plays. A programme credits thirty-two people and a dog. A review in the margin reads: “The dog understood the ending.”']],
 keepsake:['The underground theatre programme','A programme stained with stage paint. The cast photographs show people who look tired and very pleased with themselves. Nobody in it is wearing a security badge.']},
 {title:'The Quiet Line',color:[.87,.71,.49],count:62,hold:28,
 names:['FINAL REFUGE','WEST DISCONNECT','STORED MEDIUM','EAST DISCONNECT','MANUAL CONTROL','RETURN BUS','DESTRUCTION VAULT','COURIER WINDOW','DAYLIGHT GATE'],
 brief:'Physically isolate the documented last circuit, destroy its carrier medium, and return to Mara.',
 ending:'The inland loop is physically severed at both ends. The stored carrier medium burns behind the vault glass; the exposed dead are still. Mara opens the daylight gate herself. Rook is at the hospital with the twelve patients. Months later, the signed originals and her testimony bring the trial into a public hearing. Voss answers under his own name. The nine residents are returned to their families by theirs. Alex takes a daytime job. At his first ordinary family dinner, Mara asks him to pass the salt. For the first time since that call, he answers without fear. DEAD AIR — THE END.',
 scene:[['10:14 / THE QUIET LINE','The last procedure','The evidence has left the valley. Mara waits at the daylight gate. Alex lays out a procedure with no remote commands: isolate both ends, destroy the stored medium, verify the physical gap, then leave.'],['NO CONFIRMATION REQUIRED','Come back for yourself','ECHO repeats a familiar phrase from the control-room speaker. Alex removes the speaker fuse. The room does not become safe. It becomes quiet enough to think. You know the route home.']],
 objects:['Manual demolition key','Stored-medium inventory','Isolation diagram','Disconnect WEST','Disconnect EAST','Ground RETURN','Destruction-vault release','Carrier destruction charge','Courier receipt from Mara','Carrier-medium destruction','Physical-gap verification','Mara’s daylight gate'],
 order:['b','a','c'],sequenceHint:'Final isolation: EAST → WEST → RETURN. Verify both physical breaks before destroying the stored medium. No radio confirmation is required.',
 revelations:['The inventory matches the diagram: one loop, one stored medium, no secondary feed. You have accounted for the whole machine.','MARA / written receipt: “The packet is at the hospital. I am at the daylight gate. You can stop carrying all of it now.”','The gap is visible. The medium is gone. The machinery cannot answer. Leave the console; the last thing to do is walk home.'],
 lore:[['Day-shift request','Alex’s old transfer request is filed here. Reason: “I would like to have dinner while other people are having dinner.” It was declined for operational necessity. He writes WITHDRAWN across it.'],['A spare key','A technician hid a spare house key inside an electrical cabinet because he kept losing it. The tag gives no address. Beside it: “If found, tell me where I live. I have been here too long.”'],['The bench at the gate','Workers carried a bench to the daylight gate without a work order. When management asked who authorized it, every shift signed the form. It is still here. There is room for two.']],
 keepsake:['Alex’s withdrawn transfer request','A form that used to be a request for permission. On the back, Alex writes a dinner date. Mara adds: “Do not be late.”']}
];
chapters[6].ending='The coast answers with wind and waves. Mara counts twelve breathing passengers. Relay 6 and Breakwater are finished; their rescue was real. A collapsed inland road blocks the hospital route. In the civil-defence folder, a signed warning predates the outbreak by eleven days. You have stopped the call. Now find out who let it happen.';
const earlyLore=[
 [['The kettle fund','The night crew kept a coin jar for a kettle that never arrived. Mara bought one herself and left the jar for birthdays. The latest card is addressed to Alex.'],['A maintenance superstition','Never name a pump after a living person. Nobody remembers why. Three pumps are named after the same supervisor anyway.']],
 [['The missing sandwich','A twenty-year investigation into a stolen sandwich fills six maintenance binders. The last entry, in a new hand: “Dad, it was me.”'],['A pocket of silence','A worker marked the one spot beneath the duct where the fans cancelled each other out. They stood there to call home after every shift.']],
 [['The union guitar','A guitar with three strings lived in the turbine break room. Every shift learned the same song badly. A note asks the day crew to stop improving it.'],['An unfinished course','An electrician’s mathematics workbook sits beside a university acceptance letter. The first page of the next chapter is blank.']],
 [['The wall of holidays','The transmission crew pinned holiday postcards beside their rota. Most were sent from the next town. The rule was that one day away still counted.'],['A retirement speech','“I will not miss the alarms. I will miss everyone who ever came running.” The speaker retired two weeks before quarantine.']],
 [['The freight cat','A cat named Invoice lived at dispatch. Its food appears in the accounts as rodent deterrence, then staff welfare, then director’s hospitality.'],['A train to nowhere','Children drew imaginary railway routes on the backs of timetable sheets. One ends at THE MOON. Someone has carefully calculated the fare.']],
 [['Quiet visiting hours','The nurses kept an unofficial visiting hour for people who worked nights. A small lamp in the window meant someone would open the side door.'],['The good pen','A doctor labelled her pen BAD PEN so nobody would steal it. Four nurses labelled theirs WORSE PEN. The patient feedback box contains all five.']],
 [['Keeper’s weather book','Forty years of wind and cloud, interrupted by one line: “She said yes.” On the next page, the weather resumes.'],['The lighthouse race','The keeper’s children raced the beam around the lodge. Their wall chart eventually admits the lighthouse always won. They kept racing anyway.']]
];
for(let k=0;k<longNight.length;k++){
 const d=longNight[k],ch=7+k,rs=[];
 // Three connected rows; offsets and door locations are authored per chapter.
 const widths=[[12,13,12],[13,12,13],[12,12,13],[13,13,12],[12,13,13],[13,12,12],[13,13,13]][k];
 for(let j=0;j<9;j++){const col=j%3,row=Math.floor(j/3);rs.push([d.names[j],1+col*17,1+row*14,widths[col],10+(j+k)%2]);}
 const links=[];
 for(let row=0;row<3;row++)for(let col=0;col<2;col++){
  const a=row*3+col,b=a+1,r=rs[a],t=rs[b],y=r[2]+4+(k+row)%3,x=r[1]+r[3];
  links.push([x,y,t[1]-1,y,x+1,y,d.names[b]+' seal',a===0?'safe':b===8?'need:release':row===2?'need:access':undefined]);
 }
 for(let row=0;row<2;row++)for(let col=0;col<3;col++){
  const a=row*3+col,b=a+3,r=rs[a],t=rs[b],x=r[1]+5+(k+col)%3,y=r[2]+r[4];
  links.push([x,y,x,t[2]-1,x,y+1,d.names[b]+' stair',a===0?'safe':b===8?'need:release':row===1?'need:access':undefined]);
 }
 const at=(room,dx=4,dy=4)=>[rs[room][1]+dx+.5,rs[room][2]+dy+.5];
 const ids=['key','record','route','a','b','c','access','proof','consent','control','release','exit'];
 const where=[1,2,3,1,5,3,4,6,7,4,1,8];
 const positions=[[4,4],[7,4],[4,7],[8,7],[8,4],[8,4],[4,4],[7,7],[7,4],[8,7],[4,7],[7,7]];
 const actions=ids.map((id,j)=>[id,...at(where[j],...positions[j]),['key','proof','consent'].includes(id)?'handle':id==='exit'?'schematic':'terminal',d.objects[j]]);
 const needs={key:[],record:[],route:['record'],a:['key','route'],b:['key','route'],c:['key','route'],access:['record','a','b','c'],proof:['access'],consent:['access'],control:['proof','consent'],release:['control'],exit:['release']};
 const steps=Object.fromEntries(ids.map((id,j)=>[id,{id,name:d.objects[j],room:d.names[where[j]],needs:needs[id],text:id==='record'?d.revelations[0]:id==='proof'?d.revelations[1]:id==='consent'?d.revelations[2]:id==='route'?d.sequenceHint:''}]));
 chapters.push({...d,width:50,height:43,rooms:rs,links,actions,steps,duration:d.hold,
  notes:[d.brief+' '+d.sequenceHint,'Field procedure: inspect the record, find the key, and read the route card. Complete the three ordered controls, then release the lower wing at the central station. Recover both lower-wing documents. Start the central cycle, verify the release at the upper station, and use the exit.',d.revelations[0]]});
 secretOrders.push([['b','a','c'],['c','a','b'],['a','c','b']][k%3]);
 const roman={a:'I',b:'II',c:'III'};
 secretStories.push('SERVICE CIPHER: '+secretOrders[ch].map(x=>roman[x]).join(' → ')+'. '+d.lore[2][1]);
}
for(const ch of [9,10]){
 const c=chapters[ch],labels=ch===9?['BLUE','AMBER','WHITE']:['HIGH','LOW','RETURN'];
 c.circuit={masks:[3,6,4],target:1,labels};
 c.sequenceHint='COUPLED CIRCUIT: '+labels[0]+' toggles '+labels[0]+' and '+labels[1]+'. '+labels[1]+' toggles '+labels[1]+' and '+labels[2]+'. '+labels[2]+' toggles only itself. Required lamps: '+labels[0]+' ON; '+labels[1]+' OFF; '+labels[2]+' OFF. Controls can be changed freely.';
 c.steps.route.text=c.sequenceHint;c.notes[0]=c.brief+' '+c.sequenceHint;
}
const endingPages=[
 ['THE LAST WIRE / DAYLIGHT','No reply required','Both ends of the inland loop are severed. Its stored carrier medium is destroyed. The coast remains silent. Mara opens the gate herself. Alex leaves the receiver on the console and walks toward her.'],
 ['MONTHS LATER / PUBLIC HEARING','Under their own names','The signed originals and Inez Rook’s testimony bring the trial into a public hearing. Voss answers under his own name. The nine residents are returned to their families by theirs. The twelve patients from Salt Ward are alive. Rook testifies in person, including about her own part in building ECHO.'],
 ['AN ORDINARY EVENING','Pass the salt','Alex takes a daytime job. At his first ordinary family dinner, Mara asks him to pass the salt. For the first time since that call, he answers without fear. There is no final transmission. There is only the rest of their lives. DEAD AIR — THE END.']
];
