import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(source);
const gradient={addColorStop(){}};
const ctx=new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4),width:w,height:h}),createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(o,k){return k in o?o[k]:()=>{};}});
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{id,value:id==='volume'?'55':id==='brightness'?'105':'4',checked:id==='captionSetting',classList:{add(){},remove(){},toggle(){}},style:{},getContext:()=>ctx,addEventListener(){},replaceChildren(){},append(){},focus(){},requestPointerLock:()=>Promise.resolve(),width:800,height:450});return elements.get(id);}
const storage=new Map(),document={getElementById:el,createElement:()=>({...el('dummy'),style:{}}),addEventListener(){},pointerLockElement:null,hidden:false};
const context=vm.createContext({console,document,window:{addEventListener(){}},HTMLInputElement:class{},requestAnimationFrame(){},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},confirm:()=>true,Float32Array,Math,JSON,Map,Promise});
vm.runInContext(source,context);
const run=code=>vm.runInContext(code,context);
let passed=0;
function test(name,fn){run('applyLayout(0);state=fresh(); resetTransient(); maskField=null; mode="play"; keys={}; captions=[];');fn();console.log('PASS',name);passed++;}
test('single file: no external scripts, assets or fonts',()=>{assert(!/<script[^>]+src=/.test(html));assert(!/<link[^>]+href=/.test(html));assert(!/fetch\(/.test(source));});
test('movement progresses without mouse capture or fullscreen',()=>{run('keys.KeyW=true; for(let i=0;i<60;i++)update(1/60)');assert(run('state.p.x')>7);});
test('diagonal speed is normalized',()=>{const a=run('state.p={...state.p,x:5,y:18}; keys={KeyW:true}; update(.1);state.p.x-5');run('state=fresh();state.p={...state.p,x:5,y:18};keys={KeyW:true,KeyD:true};update(.1)');assert(Math.abs(run('Math.hypot(state.p.x-5,state.p.y-18)')-a)<.001);});
test('closed door blocks player collision',()=>{run('state.p.x=8.7;state.p.y=4.5;keys.KeyW=true;for(let i=0;i<120;i++)update(1/60)');assert(run('state.p.x')<9);});
test('closed heavy door attenuates sound more than open',()=>{const closed=run('received(field(8.5,4.5,25),{x:10.5,y:4.5})');const open=run('state.doors[0].open=true;received(field(8.5,4.5,25),{x:10.5,y:4.5})');assert(open-closed>=9);});
test('concrete blocks direct sound propagation',()=>{assert(run('received(field(7.5,6.5,5),{x:7.5,y:13.5})')<0);});
test('nearby Shambler investigates sound origin',()=>{run('state.enemies[0].x=23.5;state.enemies[0].y=4.5;sound(26.5,4.5,12,"bottle")');assert.equal(run('state.enemies[0].state'),'investigate');assert.equal(run('state.enemies[0].target.x'),26.5);});
test('pump masking suppresses quieter footsteps',()=>{run('const e=state.enemies[1];e.x=6.5;e.y=19.5;maskField=field(5.5,19.5,20);sound(7.5,19.5,5,"footstep")');assert.equal(run('state.enemies[1].state'),'idle');run('sound(7.5,19.5,27,"gunshot")');assert.equal(run('state.enemies[1].state'),'investigate');});
test('Runner investigates footsteps and machinery',()=>{run('state.enemies[3].x=6.5;state.enemies[3].y=19.5;sound(5.5,19.5,20,"footstep")');assert.equal(run('state.enemies[3].state'),'investigate');run('sound(5.5,19.5,20,"machinery")');assert.equal(run('state.enemies[3].state'),'investigate');});
test('pistol hits, staggers and kills in two shots',()=>{run('state.p={...state.p,x:23.5,y:4.5,a:0};state.enemies[0].x=25.5;state.enemies[0].y=4.5;fire()');assert.equal(run('state.enemies[0].hp'),35);assert.equal(run('state.enemies[0].stagger'),.35);run('state.cooldown=0;fire()');assert.equal(run('state.enemies[0].hp'),0);assert.equal(run('state.mag[0]'),6);});
test('closed door blocks bullets',()=>{run('state.p={...state.p,x:17.5,y:4.5,a:0};state.enemies[0].x=20.5;state.enemies[0].y=4.5;fire()');assert.equal(run('state.enemies[0].hp'),70);});
test('empty trigger spends no ammo and sends no gunshot',()=>{run('state.mag[0]=0;fire()');assert.equal(run('state.mag[0]'),0);assert.equal(run('state.shots'),0);});
test('reload conserves remaining magazine ammo',()=>{run('state.mag[0]=5;state.reserve[0]=2;reload();for(let i=0;i<80;i++)update(1/60)');assert.equal(run('state.mag[0]'),7);assert.equal(run('state.reserve[0]'),0);});
test('wedge can be placed and recovered',()=>{run('state.p={...state.p,x:8,y:4.5,a:0};wedge()');assert.equal(run('state.wedges'),2);assert.equal(run('state.doors[0].wedged'),true);run('wedge()');assert.equal(run('state.wedges'),3);});
test('locked archive cannot be entered before drainage',()=>{run('state.p={...state.p,x:25.5,y:13,a:Math.PI/2};interact()');assert.equal(run('state.doors.find(d=>d.x===25&&d.y===14).open'),false);});
test('objective integration: handle, pump, pause, drain, schematic, return',()=>{run('state.enemies.forEach(e=>e.hp=0);state.p={...state.p,x:27,y:3.5,a:0};interact()');assert.equal(run('state.handle'),true);run('state.p={...state.p,x:5.5,y:18,a:Math.PI/2};interact();for(let i=0;i<600;i++)update(1/60);interact()');assert.equal(run('state.running'),false);const progress=run('state.drain');run('for(let i=0;i<120;i++)update(1/60)');assert.equal(run('state.drain'),progress);run('interact();for(let i=0;i<4000;i++)update(1/60)');assert.equal(run('state.drain'),75);assert.equal(run('state.doors.filter(d=>d.archive&&d.locked).length'),0);run('state.p={...state.p,x:27,y:22.5,a:0};interact()');assert.equal(run('state.schematic'),true);run('state.p={...state.p,x:5,y:3.5,a:Math.PI};interact()');assert.equal(run('state.won'),true);assert.equal(run('mode'),'complete');});
test('checkpoint round-trip restores progress and equipment',()=>{run('state.handle=true;state.mag[0]=3;state.doors[1].open=true;save();state=fresh();loadSave()');assert.equal(run('state.handle'),true);assert.equal(run('state.mag[0]'),3);assert.equal(run('state.doors[1].open'),true);});
test('invalid saved state rejected',()=>{assert.equal(run('valid({version:1})'),false);assert.equal(run('state.mag[0]=-2;valid(state)'),false);});
test('safe room blocks enemy routing',()=>{assert.equal(run('route(state.enemies[0],{x:5.5,y:4.5}).length'),0);});
test('all objective rooms connected with unlocked doors',()=>{assert(run('state.doors.forEach(d=>{d.locked=false;d.open=true;d.safe=false});route({x:10.5,y:4.5},{x:28.5,y:22.5}).length')>0);assert(run('route({x:10.5,y:4.5},{x:5.5,y:19.5}).length')>0);assert(run('route({x:5.5,y:19.5},{x:28.5,y:3.5}).length')>0);});
test('render routine and HUD execute against canvas contract',()=>{run('draw();drawMap()');assert.equal(typeof el('objective').textContent,'string');});
test('minimap renders without showing enemy positions',()=>{run('drawMinimap()');const mini=source.slice(source.indexOf('function drawMinimap(){'),source.indexOf('function drawMap(){'));assert(!mini.includes('state.enemies'));});
test('journal reading records discoveries and pauses simulation mode',()=>{run('state.p={...state.p,x:6,y:2.5,a:0};interact()');assert.equal(run('mode'),'journal');assert.equal(run('state.notes.includes("note1")'),true);run('resume(false)');assert.equal(run('mode'),'play');});
test('legacy checkpoint without journal remains loadable',()=>{run('delete state.notes;checkpoint=snapshot();loadSave()');assert.equal(run('Array.isArray(state.notes)'),true);assert.equal(run('valid(state)'),true);});
test('malformed enemy target, missing cooldown and invalid emitter rejected',()=>{assert.equal(run('state.enemies[0].target={x:NaN,y:4};valid(state)'),false);assert.equal(run('state=fresh();delete state.cooldown;valid(state)'),false);assert.equal(run('state=fresh();state.emitters=[{x:2,y:2,type:"maker",delay:0,life:3,next:"bad"}];valid(state)'),false);});
test('save cannot place player inside concrete',()=>{assert.equal(run('state.p.x=9.5;state.p.y=6.5;valid(state)'),false);});
test('load clears stale pump masking before next simulation tick',()=>{run('checkpoint=snapshot();maskField=field(5.5,19.5,20);loadSave()');assert.equal(run('maskField'),null);});
test('closed maintenance sanctuary does not broadcast gunfire to enemies',()=>{run('state.enemies[0].x=10.5;state.enemies[0].y=4.5;sound(8.5,4.5,35,"gunshot")');assert.equal(run('state.enemies[0].state'),'idle');});
test('idle enemies begin authored local patrols',()=>{run('state.enemies[0].patrol=0;updateEnemies(.1)');assert.equal(run('state.enemies[0].state'),'patrol');assert(run('state.enemies[0].target')!==null);});
test('search expires instead of refreshing indefinitely',()=>{run('state.enemies[0].x=22.5;state.enemies[0].state="search";state.enemies[0].lastHeard={x:24,y:5};state.enemies[0].target=null;state.enemies[0].memory=.1;updateEnemies(.2)');assert.equal(run('state.enemies[0].state'),'return');});
test('door cannot close around the player',()=>{run('state.doors[0].open=true;state.p={...state.p,x:9.25,y:4.5,a:0};interact()');assert.equal(run('state.doors[0].open'),true);});
test('journal notes survive checkpoint round-trip',()=>{run('state.notes=["note1"];save();state=fresh();loadSave()');assert.equal(run('state.notes[0]'),'note1');});


test('aiming slows movement without preventing normalized control',()=>{run('aimToggle=true;keys.KeyW=true;update(.1)');assert(Math.abs(run('state.p.x-5.5')-.304)<.001);run('aimToggle=false');});
test('open maintenance airlock transmits sound normally',()=>{run('state.doors[0].open=true;state.enemies[0].x=10.5;state.enemies[0].y=4.5;sound(8.5,4.5,27,"gunshot")');assert.equal(run('state.enemies[0].state'),'investigate');});
const navigation=fs.readFileSync(new URL('./navigation-check.js',import.meta.url),'utf8');
test('navigated expedition with live enemies',()=>{console.log('Expedition result:',run(navigation));});
test('vertical aim must intersect the visible enemy',()=>{run('state.p={...state.p,x:21.5,y:4.5,a:0};state.enemies[0].x=28.5;state.enemies[0].y=4.5;lookPitch=-.23;fire()');assert.equal(run('state.enemies[0].hp'),70);run('lookPitch=0;state.cooldown=0;fire()');assert.equal(run('state.enemies[0].hp'),35);});

test('unlocked left click only requests capture and cannot spend ammunition',()=>{run('document.pointerLockElement=null;handleCanvasMouseDown({button:0,preventDefault(){}})');assert.equal(run('state.mag[0]'),8);assert.equal(run('state.shots'),0);assert.equal(run('noiseTimer'),0);assert.equal(run('keys.Mouse0'),false);});
test('already captured left click fires and starts held fire',()=>{run('document.pointerLockElement=canvas;handleCanvasMouseDown({button:0,preventDefault(){}})');assert.equal(run('state.mag[0]'),7);assert.equal(run('state.shots'),1);assert.equal(run('keys.Mouse0'),true);run('document.pointerLockElement=null');});
test('returning from journal cannot shoot during recapture',()=>{run('openJournal();resume(false);document.pointerLockElement=null;handleCanvasMouseDown({button:0,preventDefault(){}});update(1/60)');assert.equal(run('state.shots'),0);assert.equal(run('state.mag[0]'),8);});
test('unlocked right click neither aims nor fires',()=>{run('document.pointerLockElement=null;handleCanvasMouseDown({button:2,preventDefault(){}})');assert.equal(run('state.shots'),0);assert.equal(run('!!keys.Mouse2'),false);});
test('visible water lowers monotonically and clamps at drainage bounds',()=>{const full=run('drainageVisual(0)'),half=run('drainageVisual(37.5)'),empty=run('drainageVisual(75)');assert(full.archiveLevel>half.archiveLevel&&half.archiveLevel>empty.archiveLevel);assert(full.sumpLevel>half.sumpLevel&&half.sumpLevel>empty.sumpLevel);assert.equal(empty.remaining,0);assert.equal(run('drainageVisual(99).remaining'),0);assert.equal(run('drainageVisual(-1).remaining'),1);});
test('fallback wall texture orientation is corrected for opposite faces',()=>{assert.equal(run('wallU({u:.25,side:0},1,0)'),.75);assert.equal(run('wallU({u:.25,side:0},-1,0)'),.25);assert.equal(run('wallU({u:.25,side:1},0,-1)'),.75);assert.equal(run('wallU({u:.25,side:1},0,1)'),.25);});
test('3D shot height rejects aiming over enemies and respects crouching',()=>{run('scene3D={name:"test"};state.enemies[0].x=10.5;state.enemies[0].y=4.5;lookPitch=-.23');assert.equal(run('aimIntersects(state.enemies[0])'),false);run('lookPitch=0;state.p.crouch=true');assert.equal(run('aimIntersects(state.enemies[0])'),true);run('scene3D=null;lookPitch=0');});
test('complete navigation remains viable with the 3D shot contract',()=>{run('scene3D={name:"test"}');console.log('3D expedition result:',run(navigation));run('scene3D=null');});
test('new expedition has fourteen zombies and three distinct classes',()=>{assert.equal(run('state.enemies.length'),14);assert.deepEqual([...run('[...new Set(state.enemies.map(e=>e.type))].sort()')],['brute','runner','shambler']);assert.equal(run('state.enemies.find(e=>e.type==="brute").hp'),180);});
test('one shotgun shell damages three targets in its spread',()=>{run('state.p={...state.p,x:21.5,y:4.5,a:0};state.enemies.forEach(e=>e.hp=0);for(let i=0;i<3;i++){Object.assign(state.enemies[i],{x:24.5,y:4.5+(i-1)*.2,hp:70,type:"shambler"});}state.owned[1]=true;state.gun=1;lookPitch=0;fire()');assert.equal(run('state.enemies.slice(0,3).filter(e=>e.hp<=0).length'),3);assert.equal(run('state.mag[1]'),3);assert.equal(run('state.shots'),1);});
test('empty trigger reloads without a gunshot or ammo loss',()=>{run('state.mag[0]=0;fire()');assert(run('state.reload')>0);assert.equal(run('state.shots'),0);assert.equal(run('state.reserve[0]'),48);});
test('legacy four-monster checkpoint converts types and retains progress',()=>{run('state.enemies=state.enemies.slice(0,4);state.enemies.forEach((e,i)=>e.type=i===3?"crawler":"listener");state.enemies[0].hp=0;state.handle=true;state.installed=true;state.drain=30;checkpoint=snapshot();loadSave()');assert.equal(run('state.enemies.length'),4);assert.equal(run('state.enemies[0].type'),'shambler');assert.equal(run('state.enemies[3].type'),'runner');assert.equal(run('state.enemies[0].hp'),0);assert.equal(run('state.drain'),30);assert.equal(run('state.handle'),true);assert.equal(run('valid(state)'),true);});
test('pump completes in fifty running seconds',()=>{run('state.handle=true;state.installed=true;state.running=true;for(let i=0;i<499;i++)update(.1)');assert(run('state.drain')<75);run('update(.1);update(.001)');assert.equal(run('state.drain'),75);assert.equal(run('state.running'),false);});
test('campaign maps are distinct and all spawned actors are on floor',()=>{const hashes=[];for(let ch=1;ch<4;ch++){run('state=campaignState('+ch+')');assert.equal(run('valid(state)'),true);assert.equal(run('state.enemies.every(e=>!!grid[Math.floor(e.y)]?.[Math.floor(e.x)]&&!safe(e))'),true);hashes.push(run('JSON.stringify(grid)'));}assert.equal(new Set(hashes).size,3);});
test('ventilation prerequisites and paused purge retain progress',()=>{run('state=campaignState(1);campaignAction(state.items.find(i=>i.id==="control"))');assert.equal(run('state.progress.running'),false);run('for(const id of ["key","a","b","control"])campaignAction(state.items.find(i=>i.id===id));updateCampaign(10);campaignAction(state.items.find(i=>i.id==="control"));updateCampaign(10)');assert.equal(run('state.progress.timer'),10);assert.equal(run('state.doors.filter(d=>d.gate).every(d=>d.locked)'),true);run('campaignAction(state.items.find(i=>i.id==="control"));updateCampaign(20)');assert.equal(run('state.doors.filter(d=>d.gate).every(d=>!d.locked)'),true);});
test('relay order trips safely and exact order opens core vault',()=>{run('state=campaignState(2);campaignAction(state.items.find(i=>i.id==="r1"))');assert.equal(run('state.progress.flags.length'),0);run('for(const id of ["r2","r1","r3"])campaignAction(state.items.find(i=>i.id===id))');assert.equal(run('state.progress.flags.length'),3);assert.equal(run('state.doors.filter(d=>d.gate).every(d=>!d.locked)'),true);});
test('final exit requires isolation and full carrier erasure',()=>{run('state=campaignState(3);campaignAction(state.items.find(i=>i.id==="exit"))');assert.equal(run('state.won'),false);run('for(const id of ["a","b","c","control"])campaignAction(state.items.find(i=>i.id===id));updateCampaign(39)');assert.equal(run('state.doors.filter(d=>d.gate).every(d=>d.locked)'),true);run('updateCampaign(1);campaignAction(state.items.find(i=>i.id==="exit"))');assert.equal(run('state.won'),true);});
test('checkpoints validate against their own map without changing active floor',()=>{run('state=campaignState(2);checkpoint=snapshot();applyLayout(0)');assert.equal(run('valid(checkpoint)'),true);assert.equal(run('activeChapter'),0);run('loadSave()');assert.equal(run('activeChapter'),2);assert.equal(run('state.chapter'),2);});
test('invalid campaign checkpoint metadata is rejected',()=>{run('state=campaignState(1);state.progress.timer=Infinity');assert.equal(run('valid(state)'),false);run('state.progress.timer=0;state.chapter=9');assert.equal(run('valid(state)'),false);});
test('chapter transition carries gear and counters and resets local objectives',()=>{run('state.kills=9;state.shots=20;state.reserve=[70,18];completeChapter();nextChapter()');assert.equal(run('state.chapter'),1);assert.equal(run('state.kills'),9);assert.equal(run('state.reserve[0]'),70);assert.equal(run('state.progress.flags.length'),0);assert.equal(run('state.history.length'),1);assert.equal(run('checkpoint.chapter'),1);});
test('opening briefing can advance or skip without firing',()=>{run('startNew()');assert.equal(run('mode'),'prologue');run('finishPrologue()');assert.equal(run('mode'),'play');assert.equal(run('state.shots'),0);assert.equal(run('checkpoint.chapter'),0);});
test('completed legacy West Pump checkpoint offers chapter two',()=>{run('state.won=true;delete state.chapter;checkpoint=snapshot();loadSave();nextChapter()');assert.equal(run('state.chapter'),1);assert.equal(run('mode'),'play');});
const campaignNavigation=fs.readFileSync(new URL('./campaign-navigation.js',import.meta.url),'utf8');
test('navigate chapters two through seven and their secrets with enemies active',()=>{run(navigation);console.log('Campaign navigation:',run(campaignNavigation));});
test('full campaign also completes with the 3D aiming contract',()=>{run('scene3D={name:"test"}');run(navigation);console.log('3D campaign:',run(campaignNavigation));run('scene3D=null');});
test('zombie directional views select front, profiles and back',()=>{run('state.p={...state.p,x:10,y:11};state.enemies[0]={...state.enemies[0],x:10,y:10,target:{x:10,y:12}}');assert.equal(run('zombieView(state.enemies[0])'),0);run('state.p.x=11;state.p.y=10');assert.equal(run('zombieView(state.enemies[0])'),1);run('state.p.x=10;state.p.y=9');assert.equal(run('zombieView(state.enemies[0])'),2);run('state.p.x=9;state.p.y=10');assert.equal(run('zombieView(state.enemies[0])'),3);});
test('all three detailed atlases are embedded PNGs matching source assets',()=>{for(const type of ['shambler','runner','brute']){const data=run('zombieSources['+JSON.stringify(type)+']');const bytes=Buffer.from(data.split(',')[1],'base64');assert.equal(bytes.subarray(1,4).toString(),'PNG');assert(bytes.equals(fs.readFileSync(new URL('../art/zombies/'+type+'.png',import.meta.url))));}});
test('six presentation sources are embedded intact for offline play',()=>{for(const type of ['materials','pistol','shotgun','items','hero','props']){const data=run('presentationSources['+JSON.stringify(type)+']');const bytes=Buffer.from(data.split(',')[1],'base64');assert.equal(bytes.subarray(1,4).toString(),'PNG');assert(bytes.equals(fs.readFileSync(new URL('../art/presentation/'+type+'.png',import.meta.url))));}});
test('death sequences reach a persistent final pose for every class',()=>{for(const type of ['shambler','runner','brute']){run('state.enemies[0].type='+JSON.stringify(type)+';state.enemies[0].hp=0;state.enemies[0].deathTime=state.time');assert.equal(run('deathFrame(state.enemies[0])'),0);run('state.time+=.4');assert(run('deathFrame(state.enemies[0])')>0);run('state.time+=2');assert.equal(run('deathFrame(state.enemies[0])'),7);run('state.time+=50');assert.equal(run('deathFrame(state.enemies[0])'),7);}});
test('legacy corpses settle and saved death timing survives loading',()=>{run('state.enemies[0].hp=0;delete state.enemies[0].deathTime');assert.equal(run('deathFrame(state.enemies[0])'),7);run('state.enemies[0].deathTime=state.time;state.time+=.4;checkpoint=snapshot()');const frame=run('deathFrame(state.enemies[0])');run('loadSave()');assert.equal(run('deathFrame(state.enemies[0])'),frame);});
test('both reload animations advance without transferring ammunition early',()=>{for(const gun of [0,1]){run('state.gun='+gun+';state.mag[state.gun]=0;reload()');assert.equal(run('reloadFrame()'),0);run('update(state.gun?.41:.34)');assert.equal(run('reloadFrame()'),4);assert.equal(run('state.mag[state.gun]'),0);run('update(.4)');assert.equal(run('state.mag[state.gun]'),gun?1:8);assert.equal(run('state.reload>0'),!!gun);}});
test('five animation atlases are embedded byte-for-byte',()=>{for(const type of ['death-shambler','death-runner','death-brute','reload-pistol','reload-shotgun']){const data=run('animationSources['+JSON.stringify(type)+']');assert(Buffer.from(data.split(',')[1],'base64').equals(fs.readFileSync(new URL('../art/animation/'+type+'.png',import.meta.url))));}});
test('seven maps have valid spawns, unique geometry and a reachable secret reward',()=>{const hashes=[];for(let ch=0;ch<7;ch++){run(`state=campaignState(${ch});`);assert(run('valid(state)'));assert(run('state.enemies.every(e=>grid[Math.floor(e.y)]?.[Math.floor(e.x)])'));hashes.push(run('JSON.stringify(grid)'));run('state.doors.forEach(d=>{d.locked=false;d.open=true;d.safe=false})');assert(run('testRoute(state.items.find(i=>i.id==="secret-cache")).length>0'));}assert.equal(new Set(hashes).size,7);});
test('every secret enforces clue order and grants its reward only once',()=>{for(let ch=0;ch<7;ch++){run(`state=campaignState(${ch});secretAction(state.items.find(i=>i.id==='secret-cache'));`);assert.equal(run('state.secretTotal'),0);run('secretAction(state.items.find(i=>i.id==="secret-"+secretOrders[state.chapter][1]))');assert.equal(run('state.secrets.sequence.length'),0);run('for(const id of secretOrders[state.chapter])secretAction(state.items.find(i=>i.id==="secret-"+id));secretAction(state.items.find(i=>i.id==="secret-cache"));secretAction(state.items.find(i=>i.id==="secret-cache"))');assert.equal(run('state.secretTotal'),1);assert(run('state.secrets.found'));assert(run('state.doors.filter(d=>d.secret).every(d=>!d.locked)'));assert(run('valid(state)'));}});
test('v0.8 saves gain secret fixtures and weapon slots without losing progress',()=>{for(let ch=0;ch<4;ch++){run(`state=campaignState(${ch});state.notes=['note1'];state.mag[0]=3;state.items=state.items.filter(i=>!i.id.startsWith('secret-')&&!i.id.startsWith('lore-'));state.doors=state.doors.filter(d=>!d.secret);state.mag.length=state.reserve.length=state.owned.length=2;delete state.expansionVersion;delete state.secrets;delete state.projectiles;delete state.secretTotal;checkpoint=snapshot();`);assert(run('valid(checkpoint)'));run('loadSave()');assert.equal(run('state.mag[0]'),3);assert.equal(run('state.mag.length'),4);assert(run('state.items.some(i=>i.id==="secret-clue")'));assert(run('valid(state)'));}});
test('completed fourth chapter continues through a skippable fifth chapter arrival',()=>{run('state=campaignState(3);completeChapter();nextChapter()');assert.equal(run('state.chapter'),4);assert.equal(run('mode'),'prologue');run('finishPrologue()');assert.equal(run('mode'),'play');assert.equal(run('state.shots'),0);});
test('new chapter cycles require setup and preserve paused progress',()=>{for(let ch=4;ch<7;ch++){run(`state=campaignState(${ch});expansionAction(state.items.find(i=>i.id==='control'))`);assert.equal(run('state.progress.running'),false);run('for(const id of ["key",...(state.chapter===6?["c","a","b"]:["a","b"]),"control"])expansionAction(state.items.find(i=>i.id===id));updateCampaign(10);expansionAction(state.items.find(i=>i.id==="control"));updateCampaign(10)');assert.equal(run('state.progress.timer'),10);run('expansionAction(state.items.find(i=>i.id==="control"));updateCampaign(60);expansionAction(state.items.find(i=>i.id==="exit"))');assert(run('state.won'));}});
test('wrong final grounding order resets safely and remains solvable',()=>{run('state=campaignState(6);for(const id of ["key","a"])expansionAction(state.items.find(i=>i.id===id))');assert.equal(run('state.progress.flags.join()'),'key');run('for(const id of ["c","a","b","control"])expansionAction(state.items.find(i=>i.id===id))');assert(run('state.progress.running'));});
test('carbine has its own cadence, damage, capacity and reload timing',()=>{run('acquireWeapon(2);state.p={...state.p,x:23.5,y:4.5,a:0};state.enemies[0].x=25.5;state.enemies[0].y=4.5;fire();fire()');assert.equal(run('state.enemies[0].hp'),46);assert.equal(run('state.mag[2]'),23);run('state.cooldown=0;state.mag[2]=0;reload();update(.6)');assert.equal(run('state.mag[2]'),0);assert(run('expansionWeaponFrame()')>=5);run('update(.7)');assert.equal(run('state.mag[2]'),24);});
test('Spitter attack is telegraphed, interruptible and launches a moving projectile',()=>{run('state.enemies.forEach(e=>e.hp=0);Object.assign(state.enemies[0],{hp:80,type:"spitter",x:27.5,y:4.5,stagger:0});state.p={...state.p,x:23.5,y:4.5};updateSpecials(.1)');assert(run('state.enemies[0].windup>0'));assert.equal(run('state.projectiles.length'),0);run('damageEnemy(state.enemies[0],1)');assert.equal(run('state.enemies[0].windup'),0);run('state.enemies[0].stagger=0;state.enemies[0].specialCooldown=0;updateSpecials(.1);updateSpecials(.71)');assert(run('state.projectiles.some(p=>p.type==="acid")'));});
test('acid can be dodged, deals damage on contact and cannot cross closed doors',()=>{run('state.enemies.forEach(e=>e.hp=0);state.p={...state.p,x:23.5,y:4.5};spawnProjectile("acid",{x:26.5,y:4.5},state.p);state.p.y=6;for(let i=0;i<40;i++)updateSpecials(.05)');assert.equal(run('state.p.hp'),100);run('state.projectiles=[];state.p.y=4.5;spawnProjectile("acid",{x:24,y:4.5},state.p);updateSpecials(.1)');assert.equal(run('state.p.hp'),87);run('state.projectiles=[];spawnProjectile("acid",{x:17.5,y:4.5},{x:20,y:4.5});updateSpecials(.5)');assert.equal(run('state.projectiles.length'),0);});
test('Screamer call alerts nearby infected and a hit cancels its windup',()=>{run('state.enemies.forEach(e=>e.hp=0);Object.assign(state.enemies[0],{hp:90,type:"screamer",x:27.5,y:4.5,stagger:0});Object.assign(state.enemies[1],{hp:70,type:"shambler",x:27.5,y:6.5});state.p={...state.p,x:23.5,y:4.5};updateSpecials(.1);damageEnemy(state.enemies[0],1)');assert.equal(run('state.enemies[0].windup'),0);run('state.enemies[0].stagger=0;state.enemies[0].specialCooldown=0;updateSpecials(.1);updateSpecials(1.11)');assert.equal(run('state.enemies[1].state'),'chase');assert.equal(run('state.enemies[0].specialCooldown'),7);});
test('flare travels visibly, explodes on impact and respects cover',()=>{run('state.enemies.forEach(e=>e.hp=0);Object.assign(state.enemies[0],{hp:70,x:25.5,y:4.5});state.p={...state.p,x:23.5,y:4.5,a:0};acquireWeapon(3);fire()');assert.equal(run('state.mag[3]'),0);assert.equal(run('state.enemies[0].hp'),70);run('updateSpecials(.2)');assert(run('state.enemies[0].hp<=0'));assert(run('state.projectiles.some(p=>p.type==="blast")'));run('state.projectiles=[];Object.assign(state.enemies[0],{hp:70,x:19.5,y:4.5});spawnProjectile("flare",{x:17.5,y:4.5},{x:20,y:4.5});updateSpecials(.2)');assert.equal(run('state.enemies[0].hp'),70);});
test('new gear, secrets and projectiles round-trip and invalid expansion metadata is rejected',()=>{run('acquireWeapon(2);state.secrets.sequence=["a"];spawnProjectile("acid",{x:23,y:4},{x:25,y:4});save();loadSave()');assert(run('state.owned[2]'));assert.equal(run('state.secrets.sequence[0]'),'a');assert.equal(run('state.projectiles.length'),1);run('state.projectiles[0].life=Infinity');assert.equal(run('valid(state)'),false);run('state.projectiles=[];state.secrets.sequence=["bad"]');assert.equal(run('valid(state)'),false);});
test('all expansion art remains embedded byte-for-byte',()=>{for(const name of ['carbine','flare','spitter','screamer','scenes','death-spitter','death-screamer'])assert(Buffer.from(run('expansionSources['+JSON.stringify(name)+']').split(',')[1],'base64').equals(fs.readFileSync(new URL('../art/aftershock/'+name+'.png',import.meta.url))));});

test('flare follows vertical aim and impact height remains saveable',()=>{run('state.enemies.forEach(e=>e.hp=0);state.p={...state.p,x:23.5,y:4.5,a:0};acquireWeapon(3);lookPitch=.3;fire()');assert(run('state.projectiles[0].vz<0'));run('updateSpecials(.25)');assert(run('state.projectiles[0].type==="blast"'));assert(run('state.projectiles[0].height>=.05'));assert(run('valid(state)'));run('state.projectiles[0].vz=Infinity');assert.equal(run('valid(state)'),false);});
test('carbine stays in the aimed cell across repeated shots and flash settings',()=>{run('acquireWeapon(2);camera.aim=1;aimToggle=true');for(let i=0;i<12;i++){run('state.cooldown=0;fire()');assert.equal(run('expansionWeaponFrame()'),1);run('update(.04)');assert.equal(run('expansionWeaponFrame()'),1);}run('$("flashSetting").checked=true;recoil=1');assert.equal(run('expansionWeaponFrame()'),1);run('$("flashSetting").checked=false;camera.aim=0');assert.equal(run('expansionWeaponFrame()'),2);run('reload()');assert(run('expansionWeaponFrame()')>=3);});
test('all seven chapters keep decorative furniture outside door approaches',()=>{const totals=[];for(let ch=0;ch<7;ch++){run('applyLayout('+ch+');state=campaignState('+ch+')');const data=JSON.parse(run('JSON.stringify({doors:doorDefs.map(d=>({...d,horizontal:!!grid[d.y]?.[d.x-1]&&!!grid[d.y]?.[d.x+1]})),props:[...sceneryForChapter().map(p=>({x:p.x,z:p.y,w:p.type==="pipes"?.5:.9,d:.8})),...rooms.filter(r=>r.id===3||r.id===6).flatMap(r=>roomCabinets(r).map(p=>({...p,w:1.4,d:.94}))),...(activeChapter===5?rooms.slice(1).flatMap(r=>clinicBeds(r).map(p=>({...p,w:.9,d:1.9}))):[]),...(activeChapter===6?rooms.slice(1).map(r=>coastWindow(r)).filter(Boolean).map(p=>({...p,w:.1,d:2.8})):[])]})'));assert(data.props.length>0);for(const p of data.props)for(const d of data.doors){const minX=d.x+.5-(d.horizontal?2.25:.72),maxX=d.x+.5+(d.horizontal?2.25:.72),minZ=d.y+.5-(d.horizontal?.72:2.25),maxZ=d.y+.5+(d.horizontal?.72:2.25);assert(p.x+p.w/2<minX||p.x-p.w/2>maxX||p.z+p.d/2<minZ||p.z-p.d/2>maxZ,`Chapter ${ch+1} decorative obstruction`);}totals.push(data.props.length);}console.log('Clear decorative placements per chapter:',totals.join(', '));});
test('room signs relocate onto supported walls instead of spanning corridor openings',()=>{for(let ch=1;ch<7;ch++){run('state=campaignState('+ch+')');const placements=JSON.parse(run('JSON.stringify(rooms.map(r=>({r,pos:wallSignPosition(r.x+r.w/2,r.y+.012,0,1,Math.min(3,r.w-1))})))'));assert(placements.filter(p=>p.pos).length>=4);for(const {r,pos}of placements){if(!pos)continue;const width=Math.min(3,r.w-1);for(let t=-width/2;t<=width/2;t+=.1){const back=run(`grid[${Math.floor(pos.z-.08)}]?.[${Math.floor(pos.x+t)}]`);assert(!back,'Sign must have solid backing');}}}});
test('impact particles are bounded, expire, and clear when a save is loaded',()=>{run('for(let i=0;i<50;i++)impactBurst(5,1,5,true)');assert.equal(run('impactParticles.length'),96);run('updateImpactParticles(1)');assert.equal(run('impactParticles.length'),0);run('impactBurst(5,1,5);save();loadSave()');assert.equal(run('impactParticles.length'),0);});
test('cinematic advances through five shots without running gameplay',()=>{run('startNew()');const pos=run('JSON.stringify(state.p)');for(const [dt,index]of [[8,1],[7,2],[7,3],[6,4]]){run('updateIntro('+dt+')');assert.equal(run('intro.shot'),index);assert.equal(run('state.time'),0);assert.equal(run('JSON.stringify(state.p)'),pos);assert.equal(run('state.shots'),0);}run('updateIntro(4)');assert.equal(run('mode'),'play');assert.equal(run('intro.active'),false);assert.equal(run('checkpoint.chapter'),0);});
test('cinematic pause and hidden-page state freeze its timeline',()=>{run('startNew();updateIntro(3);pauseIntro();updateIntro(10)');assert.equal(run('intro.time'),3);run('pauseIntro();document.hidden=true;updateIntro(10)');assert.equal(run('intro.time'),3);run('document.hidden=false;updateIntro(1)');assert.equal(run('intro.time'),4);run('finishPrologue()');});
test('skipping and scene stepping enter play without firing',()=>{run('startNew();nextIntro();nextIntro()');assert.equal(run('intro.shot'),2);run('finishPrologue()');assert.equal(run('mode'),'play');assert.equal(run('state.mag[0]'),8);assert.equal(run('state.shots'),0);});
test('replaying the opening preserves game and saved checkpoint',()=>{run('state=campaignState(4);state.mag[0]=3;save()');const before=run('JSON.stringify(state)'),saved=run('JSON.stringify(checkpoint)');run('startIntro(true);updateIntro(12);finishPrologue()');assert.equal(run('JSON.stringify(state)'),before);assert.equal(run('JSON.stringify(checkpoint)'),saved);assert.equal(run('mode'),'pause');});
test('reduced motion keeps the cinematic camera still',()=>{run('$("motionSetting").checked=true;startNew();updateIntro(2)');assert.equal(el('introVisual').style.transform,'none');run('finishPrologue();$("motionSetting").checked=false');});
test('opening artwork is embedded intact and later chapter briefings stay manual',()=>{assert(Buffer.from(run('introSource').split(',')[1],'base64').equals(fs.readFileSync(new URL('../art/intro/opening.png',import.meta.url))));run('state=campaignState(5);startChapterScene();updateIntro(40)');assert.equal(run('mode'),'prologue');assert.equal(run('intro.active'),false);assert.equal(run('storyPage'),0);run('finishPrologue()');});
test('new chapters complete through ordinary movement with live enemies and all secrets',()=>{run(navigation);run(campaignNavigation);console.log('Long Night routes:',run(fs.readFileSync(new URL('./long-night-navigation.js',import.meta.url),'utf8')));});
test('fourteen floors validate and expanded geometry has no embedded fixtures or spawns',()=>{
 const maps=[];for(let ch=0;ch<14;ch++){run(`state=campaignState(${ch})`);assert(run('valid(state)'));assert(run('state.items.every(i=>grid[Math.floor(i.y)]?.[Math.floor(i.x)])'));assert(run('state.enemies.every(e=>grid[Math.floor(e.y)]?.[Math.floor(e.x)]&&!safe(e))'));maps.push(run('JSON.stringify(grid)'));if(ch>=7){assert.equal(run('W'),50);assert.equal(run('H'),43);assert.equal(run('rooms.length'),9);}run('drawMap();drawMinimap();draw(1/60)');}assert.equal(new Set(maps).size,14);
});
test('new objective gates refuse early entry and wrong sequences recover without resource loss',()=>{
 for(const ch of [7,8,11,12,13]){run(`state=campaignState(${ch});longAction(state.items.find(i=>i.id==='exit'));longAction(state.items.find(i=>i.id==='access'))`);assert(!run('state.won'));assert(run('state.doors.filter(d=>d.requires).every(d=>d.locked)'));run('for(const id of ["key","record","route"])longAction(state.items.find(i=>i.id===id));longAction(state.items.find(i=>i.id===chapters[state.chapter].order[1]))');assert.equal(run('state.quest.sequence.length'),0);run('for(const id of chapters[state.chapter].order)longAction(state.items.find(i=>i.id===id));longAction(state.items.find(i=>i.id==="access"))');assert(run('state.doors.filter(d=>d.requires==="access").every(d=>!d.locked)'));assert(run('state.doors.filter(d=>d.requires==="release").every(d=>d.locked)'));assert(run('valid(state)'));}
});
test('coupled circuit switches affect the displayed channels and can be reversed',()=>{
 for(const ch of [9,10]){run(`state=campaignState(${ch});for(const id of ['key','record','route'])longAction(state.items.find(i=>i.id===id));longAction(state.items.find(i=>i.id==='a'))`);assert.equal(run('state.quest.circuit'),3);assert(!run('state.quest.done.includes("a")'));run('longAction(state.items.find(i=>i.id==="a"))');assert.equal(run('state.quest.circuit'),0);run('for(const id of ["a","b","c"])longAction(state.items.find(i=>i.id===id))');assert.equal(run('state.quest.circuit'),1);assert(run('["a","b","c"].every(id=>state.quest.done.includes(id))'));assert(run('valid(state)'));}
});
test('new cycle pauses, saves, reloads and completes exactly once',()=>{
 run('state=campaignState(7);for(const id of ["key","record","route",...chapters[7].order,"access","proof","consent","control"])longAction(state.items.find(i=>i.id===id));updateLongQuest(5);longAction(state.items.find(i=>i.id==="control"));updateLongQuest(40);save();loadSave()');assert.equal(run('state.quest.cycle'),5);assert(!run('state.quest.running'));run('longAction(state.items.find(i=>i.id==="control"));updateLongQuest(100);updateLongQuest(100)');assert.equal(run('state.quest.cycle'),18);assert.equal(run('state.quest.done.filter(id=>id==="control").length'),1);assert(run('valid(state)'));
});
test('v0.9.2 saves migrate lore non-destructively including completed Breakwater saves',()=>{
 for(let ch=0;ch<7;ch++){run(`state=campaignState(${ch});state.items=state.items.filter(i=>!i.id.startsWith('lore-'));state.mag[0]=2;state.notes=['note1'];state.won=true;delete state.longNightVersion;delete state.archive;delete state.keepsakes;delete state.quest;checkpoint=snapshot()`);assert(run('valid(checkpoint)'));run('loadSave()');assert.equal(run('state.mag[0]'),2);assert(run('state.notes.includes("note1")'));assert.equal(run('state.items.filter(i=>i.id.startsWith("lore-")).length'),2);if(ch===6){run('nextChapter()');assert.equal(run('state.chapter'),7);assert.equal(run('mode'),'prologue');}}
});
test('personal keepsakes are optional, unique, saved and carried to the epilogue',()=>{
 run('state=campaignState(7);loreAction(state.items.find(i=>i.id==="keepsake"))');assert.equal(run('state.keepsakes.length'),0);run('state.notes=["lore-0","lore-1"];loreAction(state.items.find(i=>i.id==="keepsake"));loreAction(state.items.find(i=>i.id==="keepsake"));save();loadSave()');assert.equal(run('state.keepsakes.length'),1);assert.equal(run('state.archive.filter(a=>a.key.includes(":keepsake")).length'),1);run('state=campaignState(8,state)');assert.equal(run('state.keepsakes.length'),1);assert(run('state.archive.some(a=>a.title==="The last bus")'));
});
test('campaign journal closes back to completion without resuming a finished expedition',()=>{
 run('state=campaignState(13);mode="complete";openJournal();closeFieldJournal()');assert.equal(run('mode'),'complete');run('mode="pause";openJournal();closeFieldJournal()');assert.equal(run('mode'),'pause');
});
test('the final chapter has a finite three-page epilogue and no further relay',()=>{
 run('state=campaignState(13);completeChapter()');assert.equal(run('mode'),'prologue');assert.equal(run('endingPages.length'),3);run('finishPrologue();nextChapter()');assert.equal(run('state.chapter'),13);assert.equal(run('mode'),'complete');assert(run('chapters[13].ending.includes("THE END")'));run('startIntro(true);finishPrologue()');assert.equal(run('mode'),'complete');
});
test('new save rejects impossible quest dependencies and malformed circuit state',()=>{
 run('state=campaignState(7);state.quest.done=["release"]');assert(!run('valid(state)'));run('state.quest.done=[];state.quest.circuit=NaN');assert(!run('valid(state)'));run('state.quest.circuit=0;state.keepsakes=[7,7]');assert(!run('valid(state)'));
});
test('new art is embedded byte-for-byte and every new chapter has unique local lore',()=>{
 assert(Buffer.from(run('longNightSource').split(',')[1],'base64').equals(fs.readFileSync(new URL('../art/long-night/scenes.png',import.meta.url))));const titles=[];for(let ch=7;ch<14;ch++){run(`state=campaignState(${ch})`);titles.push(...run('state.items.filter(i=>i.id.startsWith("lore-")).map(i=>i.name)'));}assert.equal(new Set(titles).size,21);
});
test('all fourteen floors maintain decoration clearance at doors',()=>{
 for(let ch=0;ch<14;ch++){run(`state=campaignState(${ch})`);assert(run('sceneryForChapter().every(p=>doorwayClear(p.x,p.y,p.type==="pipes"?.5:.9,.8))'));assert(run('rooms.flatMap(r=>roomCabinets(r)).every(p=>doorwayClear(p.x,p.z,1.4,.94))'));}
});
test('new campaign routes also complete under the 3D aiming contract',()=>{
 run('scene3D={name:"test"}');run(navigation);run(campaignNavigation);console.log('3D Long Night routes:',run(fs.readFileSync(new URL('./long-night-navigation.js',import.meta.url),'utf8')));run('scene3D=null');
});

test('shotgun inserts one shell per cycle and stops after four',()=>{
 run('state.gun=1;state.mag[1]=0;state.reserve[1]=8;reload()');
 for(let shell=1;shell<=4;shell++){run('updateReload(.79)');assert.equal(run('state.mag[1]'),shell-1);run('updateReload(.01)');assert.equal(run('state.mag[1]'),shell);assert.equal(run('state.reserve[1]'),8-shell);assert.equal(run('state.reload>0'),shell<4);if(shell<4)assert.equal(run('reloadFrame()'),0);}
});
test('partial tube top-up and limited reserves never invent shells',()=>{
 run('state.gun=1;state.mag[1]=2;state.reserve[1]=1;reload();updateReload(2)');assert.equal(run('state.mag[1]'),3);assert.equal(run('state.reserve[1]'),0);assert.equal(run('state.reload'),0);run('reload()');assert.equal(run('state.reload'),0);
 run('state.reserve[1]=5;reload();updateReload(.8)');assert.equal(run('state.mag[1]'),4);assert.equal(run('state.reserve[1]'),4);assert.equal(run('state.reload'),0);
});
test('shotgun can fire a loaded shell during reload without gaining the pending shell',()=>{
 run('state.gun=1;state.mag[1]=1;state.reserve[1]=5;reload();updateReload(.4);fire()');assert.equal(run('state.reload'),0);assert.equal(run('state.mag[1]'),0);assert.equal(run('state.reserve[1]'),5);assert.equal(run('state.shots'),1);
});
test('empty trigger cannot restart or cancel the first shell insertion',()=>{
 run('state.gun=1;state.mag[1]=0;state.reserve[1]=4;fire();state.cooldown=0;updateReload(.4);fire()');assert.equal(run('state.reload'),.4);assert.equal(run('state.shots'),0);run('updateReload(.4);fire()');assert.equal(run('state.shots'),1);assert.equal(run('state.mag[1]'),0);assert.equal(run('state.reserve[1]'),3);
});
test('saving mid-reload retains inserted shells and cancels only the unfinished insertion',()=>{
 run('state.gun=1;state.mag[1]=0;state.reserve[1]=6;reload();updateReload(1.1);save();loadSave()');assert.equal(run('state.mag[1]'),1);assert.equal(run('state.reserve[1]'),5);assert.equal(run('state.reload'),0);assert(run('valid(state)'));
});
test('every full-health brute variant survives one close shotgun hit and dies to two',()=>{
 for(let id=0;id<3;id++){run(`state=fresh();state.enemies.forEach(e=>e.hp=0);state.gun=1;state.p={...state.p,x:23.5,y:4.5,a:0};Object.assign(state.enemies[0],{type:'brute',hp:enemyHealth('brute',${id}),x:25,y:4.5});fire()`);assert(run('state.enemies[0].hp>0'));run('state.cooldown=0;fire()');assert(run('state.enemies[0].hp<=0'));assert.equal(run('state.shots'),2);}
});
test('health variants distinguish fragile runners, ordinary zombies and tougher specialists',()=>{
 assert.deepEqual([...run('[0,1,2].map(id=>enemyHealth("runner",id))')],[45,50,55]);assert.deepEqual([...run('[0,1,2].map(id=>enemyHealth("shambler",id))')],[70,80,90]);assert.deepEqual([...run('[0,1,2].map(id=>enemyHealth("spitter",id))')],[100,110,120]);assert.deepEqual([...run('[0,1,2].map(id=>enemyHealth("screamer",id))')],[115,125,135]);
 run('state=campaignState(13)');assert.equal(run('new Set(state.enemies.filter(e=>e.type==="brute").map(e=>e.hp)).size'),3);
});
test('legacy enemy health migrates once, preserving wounds and dead enemies',()=>{
 run('state=fresh();delete state.combatVersion;state.enemies.forEach(e=>delete e.maxHp);Object.assign(state.enemies[0],{type:"brute",hp:70});state.enemies[1].hp=0;checkpoint=snapshot();loadSave()');assert.equal(run('state.enemies[0].hp'),85);assert.equal(run('state.enemies[0].maxHp'),170);assert.equal(run('state.enemies[1].hp'),0);run('save();loadSave()');assert.equal(run('state.enemies[0].hp'),85);assert(run('valid(state)'));
});
console.log(`\n${passed} checks passed. Simulation checks do not replace browser/listening playtests.`);
